sudo: required
services:
  - docker

before_install:
  - docker build -t trebsirk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run trebsirk/react-test npm test -- --coverage

after_success:
  - docker build -t trebsirk/multi-client ./client
  - docker build -t trebsirk/multi-server ./server
  - docker build -t trebsirk/multi-nginx ./nginx
  - docker build -t trebsirk/multi-worker ./worker
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push these images to dockerhub
  - docker push trebsirk/multi-client
  - docker push trebsirk/multi-nginx
  - docker push trebsirk/multi-server
  - docker push trebsirk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-040323213445
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
